---
title: "Organizing downloaded MEFEC data"
author: "K. Zamzow"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE, message =FALSE, warning=FALSE, error = FALSE, eval=FALSE)
```

```{r pac.ages, eval=FALSE}
install.packages(c("httr", "jsonlite", "dplyr"))
```

```{r libraries}
library(httr)
library(jsonlite)
library(dplyr)
```

```{r}
base_dir<-"~/Chemical & physical environments/Alaska weather/Mat Valley weather"
```

```{r set up to get data directly from xmacis}
#from AI
get_xmacis_data <- function(sid, sdate, edate, elems) {
  url <- "http://data.rcc-acis.org/StnData"
  
  body <- list(
    sid = sid,
    sdate = sdate,
    edate = edate,
    elems = elems
  )
  
  response <- POST(url, body = body, encode = "json")
  content <- content(response, "text")
  data <- fromJSON(content)
  
  return(data$data)
}

```

```{r run function to pull data in}
#from AI
# Set parameters
station_id <- "505733"  # This should be MEFEC
start_date <- "1917-07-05"
end_date <- "2025-01-31"
elements <- list(list(name="maxt"), list(name="mint"))

# Fetch data
temperature_data<- get_xmacis_data(station_id, start_date, end_date, elements)

#convert to data frame
temperature_df<-as.data.frame(temperature_data)

colnames(temperature_df) <- c("date", "max_temp", "min_temp")

# Display first few rows
head(temperature_df)
```

```{r save the data}
#from AI

# Save as CSV in the base_dir
write.csv(temperature_df, "MEFEC2025.02.15Temps.csv", row.names = FALSE)

```

