---
title: "Plotting MEFEC precipitation data"
author: "K. Zamzow"
date: "`r Sys.Date()`"
output: html_document
---
#This scrip places all the plots in folders for easy viewing
```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE, message =FALSE, warning=FALSE, error = FALSE, eval=FALSE)
```

#install packages and directories
```{r pac.ages, eval=FALSE}
install.packages(c("httr", "jsonlite", "dplyr", "tidyverse", "lubridate", "ggplot2"))
```

```{r libraries}

library(httr)
library(jsonlite)
library(dplyr)
library(tidyverse)
library(lubridate)
library(ggplot2)
```

```{r directories}
base_dir<-"~/Chemical & physical environments/Alaska weather/Mat Valley weather"
```

#retrieve data directly from xmacis (need internet)
```{r set up to get data directly from xmacis}
#This is pulled from the website and will only work if internet is on
#from AI
get_xmacis_data <- function(sid, sdate, edate, elems) {
  url <- "http://data.rcc-acis.org/StnData"
  
  body <- list(
    sid = sid,
    sdate = sdate,
    edate = edate,
    elems = elems
  )
  
  response <- POST(url, body = body, encode = "json")
  content <- content(response, "text")
  data <- fromJSON(content)
  
  return(data$data)
}

```

```{r run function to pull data in}
#from AI
# Set parameters. Note that "elements" must be the specific shorthand shown or you'll get an error. You can pull all of the info in from the xmacis site then select only what you want to analyze. Here I create an allElements for everything in case I want to pull stuff out later, and an elements for only precip for now

station_id <- "505733"  # This should be MEFEC
start_date <- "1917-07-05"
end_date <- "2025-01-31"
allElements <- list(list(name="pcpn"), list(name="mint"), list(name="maxt"), list(name="snow"), list(name="snwd"))
elements <- list(list(name="pcpn"))
                    
# Fetch data
pcpn_data<- get_xmacis_data(station_id, start_date, end_date, elements)

#convert to data frame
pcpn_df<-as.data.frame(pcpn_data)

colnames(pcpn_df) <- c("date", "precip")

# Display first few rows
head(pcpn_df)
```

```{r save the data}
#from AI

# Save as CSV in the base_dir
write.csv(pcpn_df, "MEFEC2025.02.16 Precip.csv", row.names = FALSE)

```

```{r ensure temperatures are seen as numbers}

Precip<-as.numeric(pcpn_df$precip, na.rm=TRUE)

```

#Saving plots in folders
```{r How to save plots, eval=FALSE}
#for information only -- apply it later in the scrip
#create directories
dir.create("plots_precip", showWarnings = FALSE)

#create lists to store them in
monthly_plots_precip <- list()

#modify the ggsave
  ggsave(
    filename = paste0("monthly_plots_precip/", month, "_pcpn_plot.png"),
    plot = plot_precip,
    width = 10,
    height = 6,
    units = "in",
    dpi = 300
  )
  
# Store precip plot in the list
  monthly_plots_precip[[month]] <- plot_precip


```

#Plot annual 30-yr rolling averages
```{r create a Month column from date, results='hide'}

library (lubridate)
library (dplyr)

Precip<-pcpn_df%>%
  mutate(
    Year = year(pcpn_df$date),
    Month = month(pcpn_df$date, label = TRUE, abbr = TRUE)
  )
#abbr=TRUE puts all the dates as 3-letter abbreviations

```

```{r install package for rolling 30 year average, eval=FALSE}
#from AI
install.packages(tibbletime)
```

```{r annual Precip rolling 30 year average}

library(tibbletime)
library(zoo)

#set up storage
dir.create("monthly_plots_precip", showWarnings = FALSE)
monthly_plots_precip <- list()

#chec/ for NAs, remove them, and count how many were removed
Precip <- Precip %>%
  filter(!is.na(precip))
Precip$precip <- as.numeric(Precip$precip)
sum(is.na(Precip$precip))

# Function to calculate 30-year average
calculate_30yr_avg <- function(data, start_year) {
  data %>%
    filter(Year >= start_year, Year < start_year + 30) %>%
    summarise(precip_30yr = mean(precip, na.rm = TRUE))
}

# Calculate for each decade
decades <- seq(1917, max(Precip$Year) - 29, by = 10)

results<- data.frame()

for (decade in decades) {
  avg <- calculate_30yr_avg(Precip, decade)
  results<- rbind(results, data.frame(start_year = decade, end_year = decade + 29, precip_30yr = avg$precip_30yr))
}

# View results
print(results)
```

```{r plot precip}
library(ggplot2)

#this is saved "manually" by exporting the image into folder "annual_plots_temp" instead of trying to automatically code it into a folder, which was having problems.

AnnualPrecip<-ggplot(data=results)+aes(x=start_year, y=precip_30yr)+
  geom_point()+
  geom_smooth(method="lm", se=FALSE, color="blue")+
  ylim(0, 0.05)+
  xlab("")+ylab("Precipitation (inches)")+
  ggtitle("Precipitation 1917-2024", subtitle= "as 30-year averages by decade")+
  theme_bw()+
  theme(axis.text.x=element_text(angle=90, hjust=1, vjust=0.5))+
  theme(axis.text=element_text(size=12))+
  theme(title = element_text(size=14))

AnnualPrecip
```

```{r save plots in folder, eval=FALSE}
#use ggsave to create a file for storage
#this doesn't seem to wor/ for annual, need to figure it out
  ggsave(
    filename = paste0("annual_plots_precip/", month, "_precip_plot.png"),
    plot = plot_temp,
    width = 10,
    height = 6,
    units = "in",
    dpi = 300
  )
  
# Store Tmax plot in the list
  annual_plots_precip[[Year]] <- plot_precip
```

#Plot 30-yr rolling averages for an individual month
```{r select a month for analysis}

DecPrecip<-Precip%>%
  filter(Month == "Dec")
DecPrecip <- DecPrecip %>%
  filter(!is.na(precip))
DecPrecip$precip <- as.numeric(DecPrecip$precip)

write.csv(DecPrecip, "MEFEC2025.02.16DecPrecip.csv", row.names = FALSE)
```

```{r Dec max temps}
#this gets to a list of results but no plot


# Function to calculate 30-year average
calculate_30yr_avg <- function(data, start_year) {
  data %>%
    filter(Year >= start_year, Year < start_year + 30) %>%
    summarise(precip_30yr = mean(precip, na.rm = TRUE))
}

# Calculate for each decade
decades <- seq(1917, max(DecPrecip$Year) - 29, by = 10)

resultsDecPrecip<- data.frame()
for (decade in decades) {
  avg <- calculate_30yr_avg(DecPrecip, decade)
  resultsDecPrecip<- rbind(resultsDecPrecip, data.frame(start_year = decade, end_year = decade + 29, precip_30yr = avg$precip_30yr))
}

# View results
print(resultsDecPrecip)
```

```{r plot DecPrecip}
library(ggplot2)
#manually exported this into precip folder

ggplot(data=resultsDecPrecip)+aes(x=start_year, y=precip_30yr)+
  geom_point()+  
  geom_smooth(method="lm", se=FALSE, color="blue")+
  ylim(0,0.05)+
  xlab("")+ylab("Precipitation (inches)")+
  ggtitle("December precipitation 1917-2024", subtitle= "as 30-year averages by decade")+
  theme_bw()+
  theme(axis.text.x=element_text(angle=90, hjust=1, vjust=0.5))+
  theme(axis.text=element_text(size=12))+
  theme(title = element_text(size=14))

```

```{r monthly Tmax and Tmin from AI placed in folders, eval=FALSE}
#this goes all the way to placing monthly plots in Tmin and Tmax folders. It should wor/ but I created two separate chun/s instead

#you need to specify months again
months <- c("Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec")
print(months)

#and ensure values are seen as numbers again
temperature_df$max_temp <- as.numeric(temperature_df$max_temp)
temperature_df$min_temp <- as.numeric(temperature_df$min_temp)


#create directories
dir.create("monthly_plots_tmax", showWarnings = FALSE)
dir.create("monthly_plots_tmin", showWarnings = FALSE)

# Create empty lists to store plots
monthly_plots_tmax <- list()
monthly_plots_tmin <- list()

# Start the for-loop
for (month in months) {
  # Filter data for the current month
  MonthTemp <- temperature_df %>%
    filter(Month == month)
  
  # Prepare and plot Tmax data
  MonthTmax <- MonthTemp %>%
    dplyr::select(date, max_temp) %>%
    mutate(
      Year = year(date),
      Month = month(date, label = TRUE, abbr = TRUE)
    )
  
  MonthTmax$max_temp <- as.numeric(MonthTmax$max_temp)
  
  # Calculate 30-year average for Tmax
  decades <- seq(1917, max(MonthTmax$Year) - 29, by = 10)
  resultsMonthTmax <- data.frame()
  
  for (decade in decades) {
    avg <- MonthTmax %>%
      filter(Year >= decade, Year < decade + 30) %>%
      summarise(max_temp_30yr = mean(max_temp, na.rm = TRUE))
    
    resultsMonthTmax <- rbind(resultsMonthTmax, 
                              data.frame(start_year = decade, 
                                         end_year = decade + 29, 
                                         max_temp_30yr = avg$max_temp_30yr))
  }
  
  # Calculate y-axis limits for Tmax
  y_min_max <- floor(min(resultsMonthTmax$max_temp_30yr))
  y_max_max <- y_min_max + 5
  
  # Create Tmax plot
  plot_tmax <- ggplot(data = resultsMonthTmax) +
    aes(x = start_year, y = max_temp_30yr) +
    geom_point() +
    geom_smooth(method = "lm", se = FALSE, color = "red") +
    ylim(y_min_max, y_max_max) +
    xlab("") + ylab("Temperature (F)") +
    ggtitle(paste("Maximum", month, "average temperatures 1917-2024"),
            subtitle = "as 30-year averages by decade") +
    theme_bw() +
    theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5),
          axis.text = element_text(size = 12),
          title = element_text(size = 14))
  
  # Save Tmax plot
  ggsave(
    filename = paste0("monthly_plots_tmax/", month, "_tmax_plot.png"),
    plot = plot_tmax,
    width = 10,
    height = 6,
    units = "in",
    dpi = 300
  )
  
  # Store Tmax plot in the list
  monthly_plots_tmax[[month]] <- plot_tmax
  
  # Repeat the process for Tmin data
  MonthTmin <- MonthTemp %>%
    dplyr::select(date, min_temp) %>%
    mutate(
      Year = year(date),
      Month = month(date, label = TRUE, abbr = TRUE)
    )
  
  MonthTmin$min_temp <- as.numeric(MonthTmin$min_temp)
  
  # Calculate 30-year average for Tmin
  resultsMonthTmin <- data.frame()
  
  for (decade in decades) {
    avg <- MonthTmin %>%
      filter(Year >= decade, Year < decade + 30) %>%
      summarise(min_temp_30yr = mean(min_temp, na.rm = TRUE))
    
    resultsMonthTmin <- rbind(resultsMonthTmin, 
                              data.frame(start_year = decade, 
                                         end_year = decade + 29, 
                                         min_temp_30yr = avg$min_temp_30yr))
  }
  
  # Calculate y-axis limits for Tmin
  y_min_min <- floor(min(resultsMonthTmin$min_temp_30yr))
  y_max_min <- y_min_min + 5
  
  # Create Tmin plot
  plot_tmin <- ggplot(data = resultsMonthTmin) +
    aes(x = start_year, y = min_temp_30yr) +
    geom_point() +
    geom_smooth(method = "lm", se = FALSE, color = "blue") +
    ylim(y_min_min, y_max_min) +
    xlab("") + ylab("Temperature (F)") +
    ggtitle(paste("Minimum", month, "average temperatures 1917-2024"),
            subtitle = "as 30-year averages by decade") +
    theme_bw() +
    theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5),
          axis.text = element_text(size = 12),
          title = element_text(size = 14))
  
  # Save Tmin plot
  ggsave(
    filename = paste0("monthly_plots_tmin/", month, "_tmin_plot.png"),
    plot = plot_tmin,
    width = 10,
    height = 6,
    units = "in",
    dpi = 300
  )
  
  # Store Tmin plot in the list
  monthly_plots_tmin[[month]] <- plot_tmin
}

```

```{r AI for monthly Precip plots to folders}
#this wor.s - don't frea/ if nothing shows in the Plots pane, chec/ the folders it is being sent to
# Create a vector of all months
months <- c("Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec")

# Create an empty list to store precip plots
monthly_plots_precip <- list()

# Create directory for precip plots
dir.create("monthly_plots_precip", showWarnings = FALSE)

#ensure values are seen as numeric
Precip$precip<-as.numeric(Precip$precip)

# Start the for-loop for precip
for (month in months) {
  # Filter data for the current month
  MonthPrecip<- Precip%>%
    filter(Month == month)
  
  # Calculate 30-year average
  decades <- seq(1917, max(MonthPrecip$Year) - 29, by = 10)
  resultsMonthPrecip<- data.frame()
  
  for (decade in decades) {
    avg <- MonthPrecip%>%
      filter(Year >= decade, Year < decade + 30) %>%
      summarise(precip_30yr = mean(precip, na.rm = TRUE))
    
    resultsMonthPrecip<- rbind(resultsMonthPrecip, 
                              data.frame(start_year = decade, 
                                         end_year = decade + 29, 
                                         precip_30yr = avg$precip_30yr))
  }
  
    
  # Calculate y-axis limits
 y_min <- floor(min(resultsMonthPrecip$precip_30yr))
 y_max <- y_min + 0.1
  
  # Create plot for the current month
  plot <- ggplot(data = resultsMonthPrecip) +
    aes(x = start_year, y = precip_30yr) +
    geom_point() +
    geom_smooth(method = "lm", se = FALSE, color = "blue") +
    ylim(y_min, y_max) +
    xlab("") + ylab("Precipitation (inches)") +
    ggtitle(paste("Precipitation", month, "1917-2024"),
            subtitle = "as 30-year averages by decade") +
    theme_bw() +
    theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5),
          axis.text = element_text(size = 12),
          title = element_text(size = 14))
  
  # Save the plot
  ggsave(
    filename = paste0("monthly_plots_precip/", month, "_precip_plot.png"),
    plot = plot,
    width = 10,
    height = 6,
    units = "in",
  )
  
  # Store the plot in the list
  monthly_plots_precip[[month]] <- plot
}
```

#Plot 30-yr rolling averages for all months, view as grid
```{r Precip for loop for each month gridplot}
#this creates a grid of each individual month with Tmax rolling average. Store it by manually exporting to the Tmax folder. Change dimensions to be 1600 wide instead of 600 wide.

# First, let's create a vector of all months
months <- c("Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec")

# Create an empty list to store plots
monthly_precip_gridplots <- list()

# Start the for-loop
for (month in months) {
  # Filter data for the current month
  MonthPrecip <- Precip%>%
    filter(Month == month)
  
  # Calculate 30-year average
  decades <- seq(1917, max(MonthPrecip$Year) - 29, by = 10)
  resultsMonthPrecip <- data.frame()
  
  for (decade in decades) {
    avg <- MonthPrecip %>%
      filter(Year >= decade, Year < decade + 30) %>%
      summarise(precip_30yr = mean(precip, na.rm = TRUE))
    
    resultsMonthPrecip <- rbind(resultsMonthPrecip, 
                              data.frame(start_year = decade, 
                                         end_year = decade + 29, 
                                         precip_30yr = avg$precip_30yr))
  }
  # Calculate y-axis limits
  y_min <- floor(min(resultsMonthPrecip$precip_30yr))
  y_max <- y_min + 0.1
  
  # Create plot for the current month
  plot <- ggplot(data = resultsMonthPrecip) +
    aes(x = start_year, y = precip_30yr) +
    geom_point() +
    geom_smooth(method = "lm", se = FALSE, color = "blue") +
    ylim(y_min, y_max) +
    xlab("") + ylab("Precipitation (inches)") +
    ggtitle(paste("Precipitation", month, "1917-2024"),
            subtitle = "as 30-year averages by decade") +
    theme_bw() +
    theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5),
          axis.text = element_text(size = 12),
          title = element_text(size = 14))
  
  # Store the plot in the list
  monthly_precip_gridplots[[month]] <- plot
}

# Display all plots (you might want to adjust the layout for better visibility)
library(gridExtra)
do.call(grid.arrange, c(monthly_precip_gridplots, ncol = 3))

```

